# Generated by Django 2.2.10 on 2020-02-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_date', models.DateTimeField(verbose_name='rate date')),
                ('CZK', models.FloatField(verbose_name='CZK rate')),
                ('EUR', models.FloatField(verbose_name='EUR rate')),
                ('PLN', models.FloatField(verbose_name='PLN rate')),
            ],
            options={
                'verbose_name': 'Currency conversion rating',
                'verbose_name_plural': 'Currencies conversion rating',
            },
        ),
    ]
